force-app/main/default/objects/ApexExecutionController__mdt/ApexExecutionController__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is created to skip the trigger for specific objects and also for all/specific users.</description>
    <label>ApexExecutionController</label>
    <pluralLabel>ApexExecutionControllers</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApexExecutionController__mdt/fields/Skip_for_All_Users__c.field-meta.xml
<CustomField>
    <fullName>Skip_for_All_Users__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To skip the trigger for all the users.</description>
    <label>Skip for All Users</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApexExecutionController__mdt/fields/Users_to_Skip__c.field-meta.xml
<CustomField>
    <fullName>Users_to_Skip__c</fullName>
    <description>To skip the trigger only for specific users</description>
    <label>Users to Skip</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/StaticFactory.cls
/*
 * @Author: Sathish SFDC
 * 
 * Purpose: 
 * StaticFactory helps to maintain the static data which can be reused instead of fetching the data for each request.
 */ 
public class StaticFactory {
    
    // Introduced the custom metadata to skip the user for trigger execution
	private static map<String, ApexExecutionController__mdt> mapAEC = new Map<String, ApexExecutionController__mdt>();
	public static map<String, ApexExecutionController__mdt> getApexExecutionController() {
		if (mapAEC.isEmpty()) {
			for (ApexExecutionController__mdt mdtAEC : [SELECT Id, MasterLabel, DeveloperName, Skip_for_All_Users__c, Users_to_Skip__c FROM ApexExecutionController__mdt]) {
				mapAEC.put(mdtAEC.MasterLabel, mdtAEC);
			}
		}
		return mapAEC;
	}

    // Fetch and return the custom metadata for the given name
	public static ApexExecutionController__mdt getApexExecutionController(String strName) {
		return getApexExecutionController().get(strName);
	}
}